### ISSUE TITLE
Fixed size copyright/permission block

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#10]
It would be best if the copyright/permission block were a fixed size, independent of the text placed in the block.  This would minimize differences in document layouts when switching from preprint (see #8) to final submission to author's version (see #9).

Perhaps also using a fixed size font (rather than `\footnotesize`, which is relative to the chosen body text font size).

**Comment by borisveytsman** [comment]
Since the copyright statements are quite different, this would create a lot of white space (the block should correspond to the most wordy statement).  

To tell the truth I see no problem with the submission having the final copyright statement.  If you wish, we can add 'Draft' watermark which suggests the final copyright statement is there for checking look and feel only.

**Comment by MatthewFluet** [comment]
Perhaps this is an aspect that is meant to be addressed by the new publishing platform, but we should check how the copyright/permission block will be handled in the near term.

Certainly, none of my recent papers have every replicated the copyright/permission block as it appeared in my camera-ready PDF submission.  Similarly, I cannot find any recent article on the ACM DL which as a copyright/permission block exactly as produced by `sig-alternate.cls`/`acmcopyright.sty`.  It seems that the publisher overprints the copyright/permission block with the "correct" (or, at least automatically generated) information.  A fixed size copyright/permission block would help with this process.

**Comment by MatthewFluet** [comment]
A fixed size copyright/permission block also minimizes the differences between page-limited submissions, where some authors might be tempted to use `\setcopyright{none}` for a little more space.

**Comment by borisveytsman** [comment]
Ok, I'll ask ACM for their opinion

**Comment by borisveytsman** [comment]
After discussion with the ACM editors it was decided that the copyright block in the review version reflects the copyright of the final product rather than of the manuscript.  This means that the authors should choose the "correct" copyright from the beginning.

**Comment by MatthewFluet** [comment]
Well, unless the documentation and compliance checking are quite strict about it, I foresee that most submissions will come in with `\setcopyright{none}` (if not `authorversion`) for space and ownership reasons.

**Comment by dbeyer** [comment]
@MatthewFluet, the following
"It seems that the publisher overprints the copyright/permission block with the "correct" (or, at least automatically generated) information."
is not a very strong argument any more, because the authors have to take care of some other entries anyway themselves (conference name, location, date, DOI) because of the "ACM Reference format" section (which is placed in the middle of the page) and therefore, this automatic processing does not "buy" us as much as before.

Previously, the authors were submitting a camera-ready paper with just a blank space (done by \toappear{}) and the processing vendor was able to automatically print all information (licensing text + conference info + DOI + ISBN + price) into that space.
The ACM offers a great API to the vendors to automatically obtain all necessary information automatically from the publishing-rights agreement of the authors with ACM.


From the authors' point of view, the advantage was that authors had to take care of the contents only and the formal stuff was done by the vendor.
From the publisher's point of view, the big advantage was correctness and consistency, because many authors are not careful with that information, which results in papers that do not match the completed publishing-rights agreement.

Question: Was there a strong rational for placing the ACM Reference format not at a fixed position together with the legal text?

**Comment by MatthewFluet** [comment]
@dbeyer I'm not an ACM official, so I wasn't privy to any of the design or requirements discussions for these core aspects of `acmart`.  My vague understanding is that ACM wants to move to a "fully automated" system where authors submit TeX sources and ACM (or the publisher) prepares the final PDF and/or HTML; under that system, the authors still wouldn't be responsible for setting the correct metadata.

I don't know about further rationale for placing the ACM Reference Format in the main body, but that certainly seems to be the natural place for that information.
