### ISSUE TITLE
Font robustness

### ISSUE THREAD

**Issue by PeterSewell** [borisveytsman/acmart#178]
My colleagues and I have just spent several hours diagnosing an issue with a paper that came out at wildly different lengths on different LaTeX installs.  It would be helpful if by default the class file fail-stopped if "libertine" and "zi4" are not available rather than almost-silently substituting quite different fonts.

**Comment by borisveytsman** [comment]
It is not easy to do with the current LaTeX font setup, which is too eager to substitute for missing fonts.  I can check whether the font styles are there, but in some systems font styles might be present, but fonts themselves might be not :(

**Comment by Blaisorblade** [comment]
After looking at this, it sounds like @PeterSewell might be remarking about `acmart`'s substitution. It does produce a class warning, but those aren't especially visible.

Looking at #39 and 760aedfae5f9d1995a22854976630552008dc0e2, it might be better to give an error, suggest using an `oldfonts` option, and explain this is not supported.

Otherwise, http://latex.org/forum/viewtopic.php?t=21884 use IfFileExists on non-sty files, but that seems only necessary on corrupted installation. The above interface issue affects valid installations as well.
