### ISSUE TITLE
Factoring out acmthm.sty

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#196]
... might not be ideal because authors are missing the file.
Previously, the nice thing was that we only needed one file: acmart.cls
Is it an option to include the code again in the class file?

**Comment by MatthewFluet** [comment]
I tend to agree that another required file (admittedly distributed with the `acmart` package, but buried alongside a dozen other `.tex`, `.png`, `.eps`, `.bib` files that are not required for a fresh document) is not ideal.

It seems that a simpler solution to #138 might be for `acmthm=false` to simply skip the `\newtheorem` declarations.  And simply add to the documentation a "Using other packages" section that simply notes that with `cleveref`, the author should `\newtheorem` their own environments (after `\usepackage{cleveref}`).

In any case, I expect a fair number of authors to `\newtheorem` their own environments anyways, since there are certainly authors who will choose different numbering schemes.  (I, for one, often have papers with just one or two theorem statements, and I find the numbering by sections to be an unnecessary level of detail.)

**Comment by MatthewFluet** [comment]
PS. By "authors `\newtheorem` their own environments", I meant to note that it would be convenient to have a simple way to not have `acmart` define the `theorem`, `lemma`, etc. environments (since they are nice names to use), but `acmart` should define the `acmplain` and `acmdefinition` theorem styles.

**Comment by borisveytsman** [comment]
@dbeyer, @MatthewFluet I am afraid I cannot agree with you.

The package is not intended to be installed by a (non-expert) user.  Rather, it is a part of a distribution like TeXLive, MacTeX or MikTeX.  A casual user would just update his or her installation, and the package will be there.  An expert user, who can run `latex acmart.ins`, probably knows what to do.

**Comment by MatthewFluet** [comment]
Except that every ACM call for papers points to http://www.acm.org/publications/proceedings-template.  As they should, by the way.  Lots of academic systems have *very* conservative update policies; `acmart` is not in the latest Ubuntu LTS.  `acmart`, for better or worse, is still changing rather rapidly; authors will need to check their papers with an up to date version, as that is what will be used to prepare the final copy of their papers.

**Comment by dbeyer** [comment]
@borisveytsman, in principle and long-term, I agree with you.
But currently, the ACM authors have to use the latest version of acmart
in order to produce consistent articles,
and for this, they have to install acmart by copying the file acmart.cls (and now also acmthm.sty)
into the folder of their paper.

Anyway, I just wanted to note this as a matter of inconvenience. If you are convinced that the overall
design is better with the separate file, then feel free to keep it.

There was an intermediate version of the old ACM style that had the legal texts factored out into 
a separate file acmcopyright.sty or so, and I was happy to see that you included 
that again into the main file.

**Comment by MatthewFluet** [comment]
To make one more argument for re-integrating `acmthm.sty`.  The original issue (#138), noted problems using `cleverref` with the theorem environments defined by `acmart`; the complicated path was to add `cleverref` to `acmart`, then remove `cleverref` from `acmart` and make it possible to define the theorem stuff via `acmthm`.  But, the only problem with `cleverref` is the actual `\newtheorem` calls.  As it stands now, a user of `cleverref` may use `acmthm=false`, but never `\usepackage{acmthm}` (and simply `\newtheorem` their own environments) and fail to use the proper `theoremstyle`.  Leaving all of the theorem style setup in `acmart` avoid that possibility.  The 7 `\newtheorem` definitions could be left in `acmart`, but guarded by the `acmthm` bool and (possibly) executed by a `\AtBeginDocument` (so that it works "out of the box" with `cleverref`).

**Comment by borisveytsman** [comment]
I guess now we can close this.
