### ISSUE TITLE
Spurious parentheses around `\citeyear`

### ISSUE THREAD

**Issue by adamsmd** [borisveytsman/acmart#243]
According to the `natbib` [documentation](http://mirrors.ctan.org/macros/latex/contrib/natbib/natbib.pdf), `\citeyear` should produce the citation year _without_ parentheses.  However, in `acmart` it produced th citation year _with_ parentheses.

## Minimum working example

`citeyear-bug.tex`:
```
\documentclass{acmart}
\begin{document}
\citeyear{TeXFAQ}
\bibliographystyle{ACM-Reference-Format}
\bibliography{citeyear-bug}
\end{document}
```

`citeyear-bug.bib`:
```
@Misc{TeXFAQ,
  title =        {{UK} List of {\TeX} Frequently Asked Questions},
  author =       {{UK \TeX{} Users Group}},
  year =         2016,
  howpublished = {\url{http://www.tex.ac.uk}}
}
```

Expected output: A PDF containing "2016"
Actual output: A PDF containing "[2016]"

## Cause

This seems to be caused by the following lines in `acmart.dtx`:
```
\if@ACM@natbib
  \let\citeN\cite
  \let\cite\citep
  \let\citeANP\citeauthor
  \let\citeNN\citeyearpar
  \let\citeyearNP\citeyear
  \let\citeyear\citeyearpar
  \let\citeNP\citealt
  \DeclareRobustCommand\citeA
     {\begingroup\NAT@swafalse
       \let\NAT@ctype\@ne\NAT@partrue\NAT@fullfalse\NAT@open\NAT@citetp}%
  \providecommand\newblock{}%
\else
  \AtBeginDocument{%
    \let\shortcite\cite%
    \providecommand\citename[1]{#1}}
\fi
```

In particular, deleting the line `\let\citeyear\citeyearpar` fixes the issue.

I wasn't able to find anywhere that the commands `\citeN`, `\citeANP`, etc. were being used in `acmart` or `natbib`.

However, I was able to find these commands defined in the [`chicago`](http://mirrors.ctan.org/biblio/bibtex/contrib/chicago/chicago.sty) bibliography style.  And indeed, the documentation for `chicago` says that `\citeyear` "produces the year information only, within parentheses".

My guess is that these commands are a holdover from an ancestor of `acmart` that wanted compatibility with `chicago`.  If these were never part of the public API of `acmart`, I think they can be safely removed.

## Recommendation

Delete the following lines:
```
  \let\citeN\cite
  \let\cite\citep
  \let\citeANP\citeauthor
  \let\citeNN\citeyearpar
  \let\citeyearNP\citeyear
  \let\citeyear\citeyearpar
  \let\citeNP\citealt
 ```

**Comment by MatthewFluet** [comment]
Similar commands were defined in `sig-alternate.cls` and `sigplanconf.cls`, and I believe that they are included in `acmart.cls` for compatibility.  In particular, I believe that `\let\cite\citep` is the critical one for our authors.  From the `natbib` documentation:

> Both \citep and \citet are defined by natbib and are thus not standard. The standard LATEX command \cite should be avoided, because it behaves like \citet for author–year citations, but like \citep for numerical ones.

Without `\let\cite\citep`, one runs into the following bad scenario.  Author writes a paper for a conference/journal using numeric citations and (understandably, since they did not explicit load `natbib` and read its documentation) simply used `\cite` everywhere; their paper came out as expected with "... the lambda calculus [4] ..." style citations.  Unfortunately, paper was rejected and author revises and resubmits for a conference/journal using author-year citations; but now their paper comes out with "... the lambda calculus Church [1932] ..." style citations.  Each and every `\cite` must be hunted down and changed to `\citep`.  (True, a conscientious author might carefully consider the context of each `\cite` and decide whether a `\citet` textual citation is appropriate, but the deadline is looming.)

**Comment by borisveytsman** [comment]
I am thinking that as the least intrusive solution I can delete `\let\citeyear\citeyearpar`.

**Comment by adamsmd** [comment]
@MatthewFluet makes a good point about `\cite`, and I agree that it should be kept.

I think we all agree that `\citeyear` should be removed.

As to `\citeN`, `\citeANP`, `\citeNN`, `\citeyearNP` and `citeNP` (and I guess `\citeA` which I overlooked before), were they ever part of the documented APIs or were they just for compatibility with even older style files?

Aesthetically, I favor getting rid of them if we don't expect too much disruption for users.  None of these are defined if `natbib` mode isn't enabled, and users can always add a `\let\citeN\cite` line to their file if they really need them.

**Comment by adamsmd** [comment]
I just tested f642df5 and it still incorrectly produces "[2016]".

@borisveytsman Did you maybe enter the wrong bug number in the commit message?  Or maybe you forgot to `git add` something?

**Comment by borisveytsman** [comment]
Sorry, forgot the main part...
