### ISSUE TITLE
Better support for non-ASCII characters when LuaLaTeX or XeLaTeX is used?

### ISSUE THREAD

**Issue by nad** [borisveytsman/acmart#255]
The fonts chosen by `acmart` have little support for non-ASCII characters when LuaLaTeX or XeLaTeX is used. For instance, consider the following UTF8-encoded file:
```latex
\documentclass{acmart}

\tracinglostchars=2

\begin{document}

$a^2$ ∀ $∀$ $\forall$

\end{document}
```
If I process this file using `lualatex`, then the following warnings are printed:
```
Missing character: There is no ∀ (U+2200) in font LinLibertineT-tlf-ot1!
Missing character: There is no ∀ (U+2200) in font LinLibertineT-tlf-t1!
```
With `xelatex` I get the following warnings:
```
Missing character: There is no ∀ in font LinLibertineT-tlf-t1!
Missing character: There is no ∀ in font LinLibertineT-tlf-ot1!
```

The problem can be partially fixed by using `fontspec`:
```latex
\usepackage[no-math]{fontspec}
\setmainfont{Linux Libertine O}
```
Now the first occurrence of `∀` is typeset, but not the second one. If I remove the `no-math` option, then the second occurrence is also typeset, but not in the same way as `$\forall$`, and the digit `2` is also typeset in a different way.

Is there some way to use `fontspec` (and perhaps `unicode-math`) to provide support for a large set of additional characters, without changing the appearance of characters that are currently supported?

**Comment by bracevac** [comment]
One solution: Consider using the [libertinus](https://www.ctan.org/pkg/libertinus-fonts) font package, which fixes bugs in Libertine and adds a proper math font version compatible with `unicode-math`. You will need to change the corresponding lines in `acmart.sty` of course. 

@borisveytsman
I wonder if the ACM would consider using the `libertinus` package instead of `libertine`+`newtxmath` (or at least add a package option). 
That would make `xetex`/`luatex`/`unicode-math` users happy. 

I would love to write conference papers with `unicode-math`, but only if there is no technical obstacle in ACM's publication processes. E.g., would it work to submit a camera ready based
on a custom `acmart` that just swaps the font? The fonts are practically identical, but the embedded font names might differ.

**Comment by arthuraa** [comment]
It would be great to see `unicode-math` supported properly in `acmart`. I've already had a few issues preparing camera-ready versions to circumvent this limitation.

**Comment by rionda** [comment]
+1. Better support for Lua and unicode-math would be a good idea.

**Comment by Blaisorblade** [comment]
Filed https://github.com/borisveytsman/acmart/issues/398 on the libertinus switch, hoping it'll get more attention.

**Comment by borisveytsman** [comment]
Works with the current latex
