### ISSUE TITLE
Duplicate date in @misc bib entries re-introduced

### ISSUE THREAD

**Issue by sampsyo** [borisveytsman/acmart#263]
As discussed in #201, commit 87395c5ed79326f7d77fb2b65a58034ca50beebf removed the duplicate date display for @misc bibliography entries. Then, it looks like PR #256 added the relevant line back in commit 0587a4cc2053bc4c9113e89ed31ad874fe91c479. I'm not very familiar with BibLaTeX, but this may have been a mistake.

**Comment by ianfoster** [comment]
This issue was also raised in Issue 142. Currently I get things like this, which looks horrible:

[n. d.]. List of File Formats. ([n. d.]). Retrieved March 1, 2018 from https: //en.wikipedia.org/wiki/List_of_ le_formats

when using:

@misc{wikipedia,
title = "List of File Formats",
url = {https://en.wikipedia.org/wiki/List_of_file_formats},
lastaccessed = {March 1, 2018}
}

[same issue if I switch to @online]

I can add a year = 2018, which is somewhat artificial, and then get the following, which isn't much better:

List of File Formats. (2018). Retrieved March 1, 2018 from https://en.wikipedia.org/wiki/List_of_ le_formats
