### ISSUE TITLE
Allow PDF metadata customization

### ISSUE THREAD

**Issue by ibnesayeed** [borisveytsman/acmart#352]
Recently, I had a situation where I could not get authors metadata in the PDF right due to some additional custom footnote markers I placed in it. I use this class for techreports and other materials that do not need to be compliant with the ACM guidelines. I wish there was a way to overwrite all or some of the PDF metadata that is derived from other existing information.

In my case, I modified the class file locally to resolve the author information issue. If this is something the maintainers of this repo would like to support, I can send a PR. Alternatively, if there is a better way to do it, please enlighten me (or better yet, document it).

**Comment by ozross** [comment]
Hello Sawood, and others

On 18 Jun 2019, at 8:50 am, Sawood Alam <notifications@github.com<mailto:notifications@github.com>> wrote:


Recently, I had a situation where I could not get authors metadata in the PDF right due to some additional custom footnote markers I placed in it. I use this class for techreports and other materials that do not need to be compliant with the ACM guidelines. I wish there was a way to overwrite all or some of the PDF metadata that is derived from other existing information.

My suggestion is for ACM and authors to consider making use of the  pdfx.sty  package.
This gives extensive ways to set XMP metadata, which overrides the PDF metadata anyway.
It does, however, force you to follow a standard such as PDF/A; but this isn’t a bad thing at all.


In my case, I modified the class file locally to resolve the author information issue. If this is something the maintainers of this repo would like to support, I can send a PR. Alternatively, if there is a better way to do it, please enlighten me (or better yet, document it).

—

Hope this helps.

Ross


Dr Ross Moore
Department of Mathematics and Statistics
12 Wally’s Walk, Level 7, Room 734
Macquarie University, NSW 2109, Australia
T: +61 2 9850 8955  |  F: +61 2 9850 8114
M:+61 407 288 255  |  E: ross.moore@mq.edu.au<mailto:ross.moore@mq.edu.au>
http://www.maths.mq.edu.au
[cid:image001.png@01D030BE.D37A46F0]
CRICOS Provider Number 00002J. Think before you print.
Please consider the environment before printing this email.

This message is intended for the addressee named and may
contain confidential information. If you are not the intended
recipient, please delete it and notify the sender. Views expressed
in this message are those of the individual sender, and are not
necessarily the views of Macquarie University. <http://mq.edu.au/>
<http://mq.edu.au/>

**Comment by borisveytsman** [comment]
The intended way to add footnote marks to author names is `\authornote`.  This commend correctly deals with the pdf tags.
