### ISSUE TITLE
Two dots when paragraph title ends with an acronym

### ISSUE THREAD

**Issue by Ko-** [borisveytsman/acmart#354]
Consider the following MWE:

```tex
\documentclass{acmart}
 
\begin{document}
\paragraph{This paragraph is the first}
\paragraph{This paragraph is the second.}
\paragraph{This paragraph is the THIRD}
\paragraph{This paragraph is the FOURTH.}
\end{document}
```
For me this gives the following output in the PDF (with the most recent version of `acmart`):
```
This paragraph is the first.
This paragraph is the second.
This paragraph is the THIRD.
This paragraph is the FOURTH..
```

If a paragraph title ends with something in all-caps, such as an acronym, and it already contained a dot, a second dot will be appended. A workaround is to not supply any dots and let `acmart` do that for you, but it would be nice if this could also automatically be corrected. (Especially when one is converting from another format to ACM format, for example.)

**Comment by borisveytsman** [comment]
LaTeX manual recommends using `\@.` instead of `.` for ending a sentence if the previous letter is an uppercase one:  see https://tex.stackexchange.com/questions/22561/what-is-the-proper-use-of-i-e-backslash-at:  `Languages like JS, HTML, etc.\ were not used by King Henry III\@.`.  With his convention your example works:
  
       Languages like JS, HTML, etc.\ were not used by King Henry III\@.

(For TeXnicians:  acmart uses spacefactor value to decide whether to put additional dot, and `\@` sets the right spacefactor)
