### ISSUE TITLE
For a name that ends in a period ("Jr."), the next comma is missing in the "Author's address" box

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#361]
I expect the Author's address will look like: `Author’s address: Chester Peterson, Jr., Miskatonic University`, but instead it looks like: `Author’s address: Chester Peterson, Jr. Miskatonic University`.

acmart `2019/04/22 v1.60`

@kseitz

```
\documentclass[acmtog]{acmart}
\acmJournal{TOG}
\setcopyright{acmlicensed}
\begin{document}
\title{Where is the comma?}

\author{Chester Peterson, Jr.}
\affiliation{%
 \institution{Miskatonic University}
 \streetaddress{Dept.\ of Computer Science}
 \city{Arkham}
 \state{MA}
 \postcode{08153}
 \country{USA}
}
\email{peterson@miskatonic.edu}

\maketitle

\section{Introduction and Conclusion}

QED\@.

\end{document}
```

**Comment by jowens** [comment]
[authorcomma.pdf](https://github.com/borisveytsman/acmart/files/3552966/authorcomma.pdf)

**Comment by kseitz** [comment]
I believe this issue is caused by the `\@addpunct` function (possibly originating from the amsgen package: http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/required/amsmath/amsgen.pdf).

From the linked documentation:

> Use of the `\@addpunct` function allows ending punctuation in section headings and elsewhere to be intelligently omitted when punctuation is already present.

In acmart.dtx, line 5840 (https://github.com/borisveytsman/acmart/blob/master/acmart.dtx#L5840), changing

`\def\institution##1{\unskip\@addpunct, ##1}%`

to

`\def\institution##1{\unskip, ##1}%`

fixes the issue, but I am unsure if this is the proper solution.

**Comment by borisveytsman** [comment]
Thanks - let's try do remove `\@addpunct`
