### ISSUE TITLE
Wrong math fonts in non-unicode compilers (after #403)

### ISSUE THREAD

**Issue by isaacsb** [borisveytsman/acmart#410]
The PR in #403 to fix #402 introduces a bug in non-unicode compilers like pdflatex: the math font gets switched back to Computer Modern. The solution is to load `newtxmath` before the text fonts in xelatex/lualatex but after them otherwise (the easiest way is to copy the `\RequirePackage[libertine]{newtxmath}` line three times, but that's ugly). Things might change if #398 is applied.

**Comment by fsaad** [comment]
@borisveytsman I've created PR #412 to address this issue, based on the suggestion by @isaacsb.  I think we should merge and create a release with the fix as soon as possible, before the wrong fonts are propagated to any document that uses Version 1.73, since the majority of users are likely to be using non-unicode compilers like pdflatex.

**Comment by adamsmd** [comment]
Since the load-order interaction of these packages is subtle and easy for future editors of the code to overlook, PR #414 adds a comment to the code pointing this out.

**Comment by borisveytsman** [comment]
Filed an emergency release
