### ISSUE TITLE
Template is broken when doi field in bibliography happens to split over a page boundary

### ISSUE THREAD

**Issue by ejgallego** [borisveytsman/acmart#444]
Dear acmart devs,

after updating to the latest template, the dreaded
```
13.13
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
fstartlink.
\@EveryShipout@Output ...@Org@Shipout \box \@cclv 
```
appears in our paper, in this concrete case:
- setup a bibliography which uses doi field
- have that biblio entry to happen as the last item of a page, in such a way that the doi link will split to the next page

This is a very serious problem as there is no way to disable the doi display, and this happens as you are working in the paper and things move.

**Comment by ozross** [comment]
Hi Emilio, Boris.

This kind of thing can happen with any hyperlink having quite long anchor text.

Try to use  \enlargethispage{..amount..}  anywhere on that page,
to keep the entire link on a single page.

Another possibility is to manually split the textual anchor, giving both parts the same target URL.
This way you have 2 links, rather than just one, with each complete on its own page.

Hope this helps.

   Ross

On 28/06/2021, at 6:34, "Emilio Jesús Gallego Arias" ***@***.******@***.***>> wrote:


Dear acmart devs,

after updating to the latest template, the dreaded

13.13
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
fstartlink.
\@EveryShipout@Output ...@Org@Shipout \box ***@***.***


appears in our paper, in this concrete case:

  *   setup a bibliography which uses doi field
  *   have that biblio entry to happen as the last item of a page, in such a way that the doi link will split to the next page

This is a very serious problem as there is no way to disable the doi display, and this happens as you are working in the paper and things move.

**Comment by ejgallego** [comment]
Hi @ozross , thanks a lot for quick reply!

Indeed, it is possible to manually workaround this problem, however, when developing a paper, this becomes very costly as any change in the layout of the paper may have the problem re-appearing.

I wonder if a more robust workaround could be implemented? Usually with biblatex it is easy to temporary disable links in the biblio, so I dunno how we could approach this.

**Comment by borisveytsman** [comment]
The kernel updates seem to improve the situation

**Comment by ejgallego** [comment]
Thanks @borisveytsman , I'm glad to hear the situation has improved.

Will ask for a reopen (and actually provide a reproducible case) if we find the problem again.
