### ISSUE TITLE
`\setcopyright{cc}`  for ACM Open Program?

### ISSUE THREAD

**Issue by florianjacob** [borisveytsman/acmart#526]
I have a question regarding the `\setcopyright{cc}` option:
My university is now part of ACM Open Program. The documentation mentions, beside the `nonacm` and `acmengage` conditions, that `\setcopyright{cc}` is applicable [in these cases](https://github.com/borisveytsman/acmart/blob/874713dfe38641353289e9ca5d884069fbd6ed18/acmart.dtx#L1048):

```
or for the authors that meet any
of the following requirements: (a)~part of the ACM Open Program;
(b)~publishing in a Gold Open Access publication;
(c)~paying the Open Access APC;
(d)~part of the Google publishing agreement.
```

However, the `cc` parameter leads to a warning in the document if neither `nonacm` nor `acmengage` is set.
I was wondering whether this is intentional, i.e., the CC copyright is typeset by ACM instead of authors in the four cases mentioned above, or whether the warning needs an update for the four new cases where CC is applicable.

Thank you  for your work!

**Comment by ept** [comment]
I just came here to ask exactly the same thing; we're also publishing Creative Commons-licensed papers via ACM Open. I've lately taken to modifying acmart.cls locally to delete [the lines that generate the warning](https://github.com/borisveytsman/acmart/blob/874713df/acmart.dtx#L5968-L5972), since otherwise the Creative Commons support seems really nice. Can we just remove the warning?

See also #515. Thanks!

**Comment by borisveytsman** [comment]
CC is now fully supported by ACM

**Comment by ept** [comment]
Wonderful, thank you @borisveytsman!

**Comment by florianjacob** [comment]
I am very happy that all I needed to fix my problems for this year's paper was an update of acmart. 😅 Thanks alot!
