### ISSUE TITLE
problems with CCS descriptors

### ISSUE THREAD

**Issue by gvdgdo** [borisveytsman/acmart#65]
There are two problems with CCS descriptors, using version 1.25 of `acmart`. 

1) the first issue is that the option `printccs=false` of `\settopmatter` is not recognised. 

2) The CCS terms do not hyphenate, thus in some occasions they run outside the column margin (and potentially in the right column). 

The attached zip file contains a tex file and related log file illustrating the two issues above. 
[Archive.zip](https://github.com/borisveytsman/acmart/files/676931/Archive.zip)

**Comment by borisveytsman** [comment]
Thanks for the report.

Issue 1 is my fault.  Will correct.

As to issue 2:  CCS terms are hyphenated;  in your example the problem is that TeX does not know how to hyphenate the word Modal.  If you add to the preamble of your document
\hyphenation{mo-d-al} (to allow breaks before and after d), it will hyphenate it.  I am not sure it is a good hyphenation, however...
