### ISSUE TITLE
Multiple affiliations and duplicate affiliations in author block

### ISSUE THREAD

**Issue by JoostvanPinxten** [borisveytsman/acmart#98]
When many authors have the same institution, or are affiliated with several institutes, it becomes tedious and space-consuming to specify all of them.

In the old version, it was suggested in the [FAQ answer 17](http://www.acm.org/sigs/publications/sigfaq#a17) to use a shared affiliation:

```latex
\numberofauthors{3}
% Three authors sharing the same affiliation.
    \author{
      \alignauthor Ben King\\      
      \email{king@cs.berkeley.edu}
%
      \alignauthor Georgia Tobin\\     
      \email{tobin@cs.berkeley.edu}
%
      \alignauthor Gerald Murray\\    
      \email{murrray@cs.berkeley.edu}
%
      \sharedaffiliation
      \affaddr{Department of Electrical Engineering and Computer Science }  \\
      \affaddr{University of California, Berkeley }   \\
      \affaddr{Berkeley, CA 94720-1776 }
          }
%
```

However, this does not work in the new version. What is the new way to specify them? In the IEEE conf class we can specify affiliation icons that relate to the different affiliations below the title.

A related question would be how to specify more than 3 authors (old FAQ answer 18) properly.

Can anyone please point me to the relevant documentation/commands, if they are available?

**Comment by MatthewFluet** [comment]
This is all described in the class documentation (which, as a generated file, is not stored in this GitHub repository).  See page 9 of http://mirrors.ctan.org/macros/latex/contrib/acmart/acmart.pdf.

**Comment by MatthewFluet** [comment]
BTW, the recommendation of acmart is to repeat affiliations for authors, rather than trying to share an affiliation block.

**Comment by JoostvanPinxten** [comment]
Thanks Matthew; I did see that, yet it does not cover multiple affiliations (only multiple departments within the same affiliation). When I add multiple affiliations between two `\author` commands, it is difficult how to distinguish them.

The papers that I write have both academic and industrial partners, some of them associated with both a university and a company. I simply do not agree with spending a third of a page on authors, when in IEEE style they fit on 5 lines...

**Comment by borisveytsman** [comment]
This is a design question.  How would you print authors with overlapping affiliations with the current ACM style so it would not be too confusing?  

One solution is to use `\authornote`, something like

```
\author{A. U. Thor}\authornote{Also with Acme, inc}
\author{C. O. Respondent}
\affiliation{\institute{North Pole Institute}}
```

**Comment by JoostvanPinxten** [comment]
This might indeed be a nice way to do it. I'll suggest it to my co-authors.

I think it can be nice to add this to the documentation as an alternative way of specifying multiple affilitations

**Comment by borisveytsman** [comment]
After some thinking I've added the command `\additionalaffiliation`, which is a little more than `\authornote`.

**Comment by JoostvanPinxten** [comment]
Thanks, I'll check it out!

**Comment by MakarovIA** [comment]
Well, adding to the first author comment, having one shared affiliation (alligning several authors) will shorten the space and look much better as it was for sig-alternate-2015 package.

**Comment by drt24** [comment]
I am also running into problems with this. I have a paper with 5 authors, all at the same institution and so it is a really simple case but this is laid out really badly by acmart. It creates only one column with all the authors and the affiliation details in it. Previously it was possible to have a bunch of authors, laid out with three per line, and then share an affiliation block for all of them.
The only supported solution to use a sensible amount of space seems to be to drop almost all the affiliation details and just give the institution and not include the email address, country or department. There needs to be some way to share affiliation information rather than repeating it.

**Comment by LiveColdSun** [comment]
I have the similar problem. I have a paper with 7 authors, say A B C D E F G, A and B are at institution  X, A C D E F G are at institution Y. Is there any better solution to provide a good layout ？

**Comment by borisveytsman** [comment]
I'd recommend splitting authors at Y:
A  B  - X . (with footnote for A about Y)
C D - Y
E F G - Y

**Comment by drt24** [comment]
Would that result in correct metadata for A?

Additionally when using the multiple authors with one affiliation style more than once then at present this makes it hard to work out what order the authors are in as you need to read down each column rather than just going right to left. It is also easy to think that one of the authors might be part of the affiliation as the affiliation and the names are not very visually distinctive.

**Comment by borisveytsman** [comment]
As to metadata:  there is a special macro `\additonalaffiliaton` to take care of this

**Comment by jttaufa** [comment]
How do we deal with multiple cross-affiliations?

Say authors A,B,C have affiliation X,Y
D has affiliation X,Y,Z
E,F have affiliation Y,Z
G,H have affiliation X,Z

A is primary author and must be listed first
C is supervising author and must be listed last (but has the same affiliations as A)

This style with non-numbered affiliations take up the whole page!

Is it possible for the same \additionalaffiliation to be shared across authors using affiliation IDs?

**Comment by TigreInsaciable** [comment]
the newest  acmart.cls manage authors like this:


\author{Marco Garc\'ia}
%\orcid{1234-5678-9012}
\affiliation{%
  \institution{Universidad Nacional de San Agust\'in}
%  \streetaddress{P.O. Box 1212}
  \city{Arequipa}
  \state{Per\'u}
%  \postcode{43017-6221}
}
\email{mgarciacar@unsa.edu.pe}

\author{Percy Huertas}
%\orcid{1234-5678-9012}
\affiliation{%
  \institution{Universidad Nacional de San Agust\'in}
%  \streetaddress{P.O. Box 1212}
  \city{Arequipa}
  \state{Per\'u}
%  \postcode{43017-6221}
}
\email{phuertas@unsa.edu.pe}

the problem comes when i want to include the subsection ADDITIONAL AUTHORS, the old version managed the additional authors like this: 


EXAMPLES
\numberofauthors{5}
.
[\author{…} 3 of the 5 goe here so as to appear beneath the title]
.
\additionalauthors{Additional authors: John Smith (The Th{\o}rvald
Group, email: {\texttt{jsmith@affiliation.org}}) and Julius
P.~Kumquat (The Kumquat Consortium, email:
{\texttt{jpkumquat@consortium.net}}).}


can someone answer the better solution for this problem.

**Comment by TigreInsaciable** [comment]
This is my solution, can be other best solution?

\section{ADDITIONAL AUTHORS}
Additional authors: Jose Fernandez (Universidad La Salle,
email: pfernand@ulasalle.edu.pe).
